# Generated by Django 5.2.14 on 2026-06-02 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_delete_parametersetwall'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParameterSetBarrier',
        ),
    ]
