# Generated by Django 5.2.14 on 2026-06-02 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_delete_parametersetbarrier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParameterSetGround',
        ),
    ]
