# Generated by Django 5.2.14 on 2026-06-02 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_delete_parametersetground'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParameterSetNotice',
        ),
    ]
