# Generated by Django 5.2.14 on 2026-06-02 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_remove_parameterset_avatar_bound_box_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='avatar_animation_speed',
        ),
    ]
