# Generated by Django 5.2.14 on 2026-06-02 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_remove_parameterset_avatar_animation_speed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametersetplayer',
            name='hex_color',
        ),
        migrations.RemoveField(
            model_name='parametersetplayer',
            name='start_x',
        ),
        migrations.RemoveField(
            model_name='parametersetplayer',
            name='start_y',
        ),
    ]
