# Generated by Django 5.2.14 on 2026-06-02 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_remove_parametersetplayer_hex_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametersetplayer',
            name='parameter_set_group',
        ),
    ]
