# Generated by Django 5.2.14 on 2026-06-03 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_remove_parametersetplayer_parameter_set_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.IntegerField(default=1, verbose_name='Period Number')),
                ('label', models.CharField(blank=True, default='Period', max_length=255, null=True, verbose_name='Label')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_periods', to='main.parameterset')),
            ],
            options={
                'verbose_name': 'Parameter Set Period',
                'verbose_name_plural': 'Parameter Set Periods',
                'ordering': ['period_number'],
                'constraints': [models.UniqueConstraint(fields=('parameter_set', 'period_number'), name='unique_parameter_set_period_number')],
            },
        ),
    ]
