# Generated by Django 5.2.14 on 2026-06-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_parametersetperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetperiod',
            name='outside_option_payout',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Outside Option Payout'),
        ),
        migrations.AddField(
            model_name='parametersetperiod',
            name='type_a_player_1',
            field=models.IntegerField(default=0, verbose_name='Type A Player 1'),
        ),
        migrations.AddField(
            model_name='parametersetperiod',
            name='type_a_player_2',
            field=models.IntegerField(default=0, verbose_name='Type A Player 2'),
        ),
        migrations.AddField(
            model_name='parametersetperiod',
            name='type_b_player_1',
            field=models.IntegerField(default=0, verbose_name='Type B Player 1'),
        ),
        migrations.AddField(
            model_name='parametersetperiod',
            name='type_b_player_2',
            field=models.IntegerField(default=0, verbose_name='Type B Player 2'),
        ),
    ]
