# Generated by Django 5.2.14 on 2026-06-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_parametersetperiod_outside_option_payout_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametersetperiod',
            old_name='type_a_player_1',
            new_name='type_a_units_player_1',
        ),
        migrations.RenameField(
            model_name='parametersetperiod',
            old_name='type_a_player_2',
            new_name='type_a_units_player_2',
        ),
        migrations.RenameField(
            model_name='parametersetperiod',
            old_name='type_b_player_1',
            new_name='type_b_units_player_1',
        ),
        migrations.RenameField(
            model_name='parametersetperiod',
            old_name='type_b_player_2',
            new_name='type_b_units_player_2',
        ),
    ]
