# Generated by Django 5.2.14 on 2026-06-03 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_rename_type_a_player_1_parametersetperiod_type_a_units_player_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametersetperiod',
            name='label',
        ),
    ]
