# Generated by Django 5.2.14 on 2026-06-03 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_remove_parametersetperiod_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametersetplayer',
            name='id_label',
        ),
    ]
