# Generated by Django 5.2.14 on 2026-06-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_remove_parametersetplayer_id_label'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParameterSetGroup',
        ),
    ]
