# Generated by Django 5.2.14 on 2026-06-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_delete_parametersetgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetperiod',
            name='pairs',
            field=models.JSONField(default=dict, verbose_name='Pairs'),
        ),
    ]
