# Generated by Django 5.2.14 on 2026-06-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_parametersetperiod_pairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetperiod',
            name='work_payout',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Work Payout'),
        ),
        migrations.AlterField(
            model_name='parametersetperiod',
            name='outside_option_payout',
            field=models.DecimalField(decimal_places=2, default=0.75, max_digits=10, verbose_name='Outside Option Payout'),
        ),
    ]
