# Generated by Django 5.2.14 on 2026-06-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0094_parametersetperiod_work_payout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='number_of_periods_paid',
            field=models.IntegerField(default=4, verbose_name='Number of periods paid'),
        ),
    ]
