# Generated by Django 5.2.14 on 2026-06-18 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_parameterset_number_of_periods_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='period_count',
        ),
    ]
