# Generated by Django 5.2.14 on 2026-06-22 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0096_remove_parameterset_period_count'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='parametersetperiod',
            name='unique_parameter_set_period_number',
        ),
    ]
