# Generated by Django 5.2.14 on 2026-06-24 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0097_remove_parametersetperiod_unique_parameter_set_period_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='break_frequency',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='break_length',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='period_length',
        ),
    ]
