# Generated by Django 5.2.14 on 2026-06-24 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0098_remove_parameterset_break_frequency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionevent',
            options={'verbose_name': 'Session Event', 'verbose_name_plural': 'Session Events'},
        ),
        migrations.RemoveField(
            model_name='sessionevent',
            name='time_remaining',
        ),
    ]
