# Generated by Django 5.2.14 on 2026-07-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_alter_sessionevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructionset',
            name='ex1_outside_option_payout',
            field=models.DecimalField(decimal_places=2, default=0.75, max_digits=10, verbose_name='Outside Option Payout'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='ex1_type_a_units_player_1',
            field=models.IntegerField(default=0, verbose_name='Type A Player 1'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='ex1_type_a_units_player_2',
            field=models.IntegerField(default=0, verbose_name='Type A Player 2'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='ex1_type_b_units_player_1',
            field=models.IntegerField(default=0, verbose_name='Type B Player 1'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='ex1_type_b_units_player_2',
            field=models.IntegerField(default=0, verbose_name='Type B Player 2'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='ex1_work_payout',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Work Payout'),
        ),
    ]
