# Generated by Django 5.2.16 on 2026-08-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_instructionset_ex1_outside_option_payout_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionevent',
            options={'ordering': ['period_number', 'timestamp'], 'verbose_name': 'Session Event', 'verbose_name_plural': 'Session Events'},
        ),
        migrations.AddField(
            model_name='instruction',
            name='quiz_answer',
            field=models.CharField(default='', max_length=255, verbose_name='Quiz Answer (CSV)'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='quiz_question',
            field=models.BooleanField(default=False, verbose_name='Quiz Question'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='ex1_part_2_accept',
            field=models.BooleanField(default=False, verbose_name='Part 2 Accept'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='ex1_part_2_offer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Part 2 Offer'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='ex1_type_a_bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Type A Bid'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='ex1_type_a_bid_counterpart',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Type A Bid Counterpart'),
        ),
    ]
