# Generated by Django 5.2.16 on 2026-08-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_alter_sessionevent_options_instruction_quiz_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructionset',
            name='ex1_type_a_bid',
            field=models.IntegerField(default=0, verbose_name='Type A Bid'),
        ),
        migrations.AlterField(
            model_name='instructionset',
            name='ex1_type_a_bid_counterpart',
            field=models.IntegerField(default=0, verbose_name='Type A Bid Counterpart'),
        ),
    ]
