# Generated by Django 5.2.16 on 2026-08-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0102_alter_instructionset_ex1_type_a_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayer',
            name='quiz_answers',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Quiz Answers'),
        ),
    ]
