# Generated by Django 5.2.16 on 2026-08-28 20:19

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0103_sessionplayer_quiz_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='quiz_state',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='State of group variables on this page if quiz question'),
        ),
    ]
