# Generated by Django 5.2.16 on 2026-09-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0104_instruction_quiz_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetplayer',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=0.01, max_digits=5, verbose_name='Exchange Rate'),
        ),
    ]
