# Generated by Django 5.2.16 on 2026-09-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0105_parametersetplayer_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetplayer',
            name='exchange_rate',
            field=models.IntegerField(default=100, verbose_name='Exchange Rate'),
        ),
    ]
