# Generated by Django 5.2.16 on 2026-09-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0107_parametersetperiod_block_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetperiod',
            name='outside_option_payout',
            field=models.CharField(default='0.20,0.25,0.30,0.35,0.40,0.45,0.55,0.65,0.75,0.90', max_length=10, verbose_name='Outside Option Payouts'),
        ),
    ]
